<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tax_receipt</name>
   <tag></tag>
   <elementGuidId>17bb519d-cde1-4a1f-87d2-2108a0143bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='tax_receipt'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e58e20e-3fb0-42b7-bcba-875fa0c2f9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>28083af7-1256-421b-8bc5-d1231b2b782a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tax_receipt</value>
      <webElementGuid>b6c1f0da-c8b9-4eae-93c3-f280c621668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ที่อยู่อื่นๆ</value>
      <webElementGuid>83ea52d9-e3be-4bd0-81fa-fd2d6de78faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(this.checked){this.form.receipt_name.disabled=false;this.form.receipt_tax_id.disabled=false;this.form.receipt_branch.disabled=false;this.form.receipt_address.disabled=false;this.form.receipt_moo.disabled=false;this.form.receipt_alley.disabled=false;this.form.receipt_road.disabled=false;this.form.receipt_subdistrict.disabled=false;this.form.receipt_district.disabled=false;this.form.receipt_province.disabled=false;this.form.receipt_postcode.disabled=false;this.form.receipt_tel.disabled=false;}</value>
      <webElementGuid>7b472ee6-9505-4b6a-8d48-5309b363c4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-light&quot;]/body[1]/section[@class=&quot;signup-area ptb-100&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;signup-form&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/input[2]</value>
      <webElementGuid>4102d8c5-9917-4a59-984a-536b3687144f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='tax_receipt'])[2]</value>
      <webElementGuid>8b613a3d-a8df-4c3e-8ffb-fbd8b6faa387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input[2]</value>
      <webElementGuid>79dfb06b-8842-43c6-bfbb-bea8c9413ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'tax_receipt']</value>
      <webElementGuid>c0bb1d49-49bf-473a-8be9-9cdb6dc8b3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tax_receipt']</value>
      <webElementGuid>01a455ed-b2b5-451a-a7bf-163643c5dd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/input</value>
      <webElementGuid>50260d66-bad7-45f1-a471-f62d71525f7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
