<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__language</name>
   <tag></tag>
   <elementGuidId>a39fbc8d-1a8f-4242-bb51-d21584881c9f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Modern Software Development Toolchains/input__language.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Modern Software Development Toolchains/input__language.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='language'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78fd036c-882e-4eb9-bf80-58116cd36832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a5e9f228-c8f5-449b-9f49-dc79698a2e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>language</value>
      <webElementGuid>fdf094c2-600d-4140-888f-b9edaefd6abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>language[]</value>
      <webElementGuid>9249bf6e-3f9e-4634-8379-b129d7d7ab9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>JavaScript</value>
      <webElementGuid>3c412c94-3f45-4a48-b157-6a260e2c493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-light&quot;]/body[1]/section[@class=&quot;signup-area ptb-100&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;signup-form&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/input[@id=&quot;language&quot;]</value>
      <webElementGuid>54dfc544-01b3-4edb-8838-1a1580813ca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='language'])[6]</value>
      <webElementGuid>5967d05f-50f4-4d1e-acd8-86e109a3d0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>1bf782fd-8400-461b-bdb8-f56302b062d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'language' and @name = 'language[]']</value>
      <webElementGuid>c6a2d4c9-92fe-4cdd-a2ea-a6855d030af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
